export const SET_KEYWORD = 'SET_KEYWORD'

export const SET_LOGINSTATUS = 'SET_LOGINSTATUS'

export const SET_USERINFO = 'SET_USERINFO'

export const SET_LOGINVISIABLE = 'SET_LOGINVISIABLE'

export const SET_LOGINFLAG = 'SET_LOGINFLAG'